### ISSUE TITLE
"Syncthing has been disabled"

### ISSUE THREAD

**Issue by swiftbird07** [MobiusSync/MobiusSync#108]
Only on iOS 16.4 I get the warning "Can't sync [...] Syncthing has been disabled.
I thought maybe its because of the 20 MB limit, but there is another bug that nothing happens if I click on "Purchase".

OS: iOS 16.4
Model: iPhone 13 Pro Max
Syncthing Version: Newest from AppStore

**Comment by SimonPickup** [comment]
Thanks for reporting.

Yes, that message is because of the 20MB limit.

We thought we had fixed a bug with the Purchase button not working #46 in the latest release. This was happening for users who had set different font sizes. Do you have any non-default settings like that?

In any case, the easy workaround is to delete **Möbius Sync** and buy **Möbius Sync Pro** instead (at the same price as in-app purchase). You will have to set up your shares again.
