### ISSUE TITLE
Files in Sandbox not visible in Files app

### ISSUE THREAD

**Issue by ghost** [MobiusSync/MobiusSync#112]
Hi,
since I installed Möbius on a new iPhone 13 mini the sandbox folder of Möbius is no longer visible in the Files app. I added a same folder from a Mac also running Syncthing - the files are synced completely.
Under "On my iPhone" in the Files app is no "Möbius Sync" folder; I remember there was one on my old iPhone where I could access my synced files and folders. Anything I'm missing here?

**Comment by SimonPickup** [comment]
Others have reported a phone reboot will help the disappearing folder to reappear.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: 5t4cktr4c3 ***@***.***>
Sent: Monday, April 24, 2023 4:09:48 PM
To: MobiusSync/MobiusSync ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MobiusSync/MobiusSync] Files in Sandbox not visible in Files app (Issue #112)


Hi,
since I installed Möbius on a new iPhone 13 mini the sandbox folder of Möbius is no longer visible in the Files app. I added a same folder from a Mac also running Syncthing - the files are synced completely.
Under "On my iPhone" in the Files app is no "Möbius Sync" folder; I remember there was one on my old iPhone where I could access my synced files and folders. Anything I'm missing here?

**Comment by ghost** [comment]
Reinstalled twice, no effect - restarting fixed it. Thanks!
