### ISSUE TITLE
Syncing Folders outside of Möbius Folder not working (iOS17)

### ISSUE THREAD

**Issue by OfficialCRUGG** [MobiusSync/MobiusSync#123]
I want to sync the Spotify Folder on my iPhone with my Mac.
I set everything up and got the in-app purchase to sync folders outside the Möbius Folder.
Set up the Sync and selected the Spotify Folder.
It synced the entire contents of the Möbius Folder (as opposed to normally a sub-folder) but not the Spotify Folder. It seems that it is trying to go as far up in the file system as it can, but can't go farther up than the Möbius Folder.
I'm on iOS 17.

**Comment by Phosfyr** [comment]
I'm on iOS 16.6 and also have this problem. I use Mobius Sync (premium unlocked) to sync Obsidian notes between my iPhone and PC. Prior to the latest iOS update, everything worked without a hitch: I had my Obsidian notes folder shared from my PC via Mobius Sync and all changes would automatically be updated on my iPhone. But now Mobius Sync is no longer able to directly access the corresponding Obsidian folder on my iPhone and can only sync files into the Mobius Sync folder. I have to manually complete the sync by copying the resulting files in the Mobius Sync folder to their proper destination in the Obsidian folder on my iPhone.

For whatever reason, it now appears that Mobius Sync is unable to access other app sandbox folders even with the experimental setting enabled. I spent a couple hours trying to troubleshoot this issue by setting up my shared folders again from scratch thinking that it was a problem on my end only to realize that nothing I did made a difference. Something to do with folder permissions might have broken in a recent iOS update.

**EDIT:** Never mind, turned out to be user error in my case. Sharing the Obsidian folder from iOS to my PC worked just fine while the reverse did not. Syncing is now working as intended.

**Comment by CapSel** [comment]
> **EDIT:** Never mind, turned out to be user error in my case. Sharing the Obsidian folder from iOS to my PC worked just fine while the reverse did not. Syncing is now working as intended.

@Phosfyr could you elaborate on your solution?

**Comment by Phosfyr** [comment]
@CapSel I used to share my Obsidian notes folder from my PC to my iPhone, which previously worked fine; however, after a recent iOS update, this setup no longer works, perhaps due to some issue with folder permissions on the iOS side that prevents Mobius Sync from directly accessing the Obsidian app sandbox folder as it could before. After a lot of trial and error, I found that sharing the Obsidian notes folder from iOS to my PC (i.e. setting the shared folder on Mobius Sync as the iOS Obsidian folder, not the one on PC) now works again like it used to. I have no idea why, but sharing from iOS -> PC allows changes to be synced directly in the app sandbox folder, while sharing a folder from PC -> iOS results in the aforementioned issues with files getting stuck in the Mobius Sync folder. I'm not sure why sharing in this direction works while the opposite causes problems, but it's clear something changed in between iOS updates that led to this happening.

I hope that makes sense!

**Comment by lifelemons** [comment]
Hello, for me 
> sharing from iOS -> PC allows changes to be synced directly in the app sandbox folder 

this method does not work on iOS 17.0.2

**Comment by roland-stojkoski** [comment]
Same here. I'm on iOS 16.6.1 and I see the following when trying to add a folder in Obsidian sandbox:

![IMG-20231015-WA0009~3.jpg](https://github.com/MobiusSync/MobiusSync/assets/25934085/932b9a57-b3b0-463d-b14a-23e340f5cdd6)

**Comment by dictionarymouse** [comment]
[This](https://github.com/MobiusSync/MobiusSync/discussions/102#discussioncomment-7343958) is the only way I got my share working. 
[This issue](https://github.com/MobiusSync/MobiusSync/issues/111) seems related (to the folder marker error).

**Comment by dictionarymouse** [comment]
> I want to sync the Spotify Folder on my iPhone with my Mac. I set everything up and got the in-app purchase to sync folders outside the Möbius Folder. Set up the Sync and selected the Spotify Folder. It synced the entire contents of the Möbius Folder (as opposed to normally a sub-folder) but not the Spotify Folder. It seems that it is trying to go as far up in the file system as it can, but can't go farther up than the Möbius Folder. I'm on iOS 17.

Yes, it does seem to be going up the file system, as if the app folders were subfolders of the Möbius folder, and it selects the folder above the one you expect. 

I think you might be able to sync Spotify if you can make a Spotify subfolder. Because just now, when I thought I had successfully setup an iPad/Obsidian/subfolder sync, I had actually setup an iPad/Obsidian/ sync. 

### to Reproduce

1. Open iPadOS _Files_ app, create a new folder in the iPad/app folder (e.g. `iPad/Obsidian/test`)
2. Open _MobiusSync_,  tap `Add Folder`
3. Name it now, let's say, _Obsidian-Test_ via `General` > `Folder Label`,  <br> ⚠️ Note: *if the Folder Label is changed later, the folder [might] lose the bookmark, which cannot be [easily] re-established* 
4. _Pick External Folder_
7. Navigate to newly created folder, e.g. `iPad/Obsidian/test`
8. Press Open. The folder, _Obsidian-Test_ is added to MöbiusSync's Folders
9. Obsidian-Test > `Open Folder` will open `iPad/Obsidian` not `iPad/Obsidian/test`

Note: I sometimes have success syncing the expected folder if it already contains content (besides empty folders)

**Update**: Apparently, I had on SyncThing on my Mac, paused the iPad while I ran this test. After re-enabling, I was prompted on the mac to accept the share. After doing so, everything seemed to sync as expected (on a relatively superficial check).

**Comment by wallynm** [comment]
I had this issue trying to sync Obsidian Vaults, and i've discovered that the Root folder of Obsidian, for somereason in my iPhone doesnt work, once i chose a subfolder, it started working as expected. Before that, i was selecting the Obsidian Folder, and Mobius was creating a copy folder inside default Sync folder, now everything is working as expected.

In my case, was some kind issue with root folder.
iPhone 15 pro
iOS: 17.4.1
Pro Mobius version: 1.23.2-41-ga6a9adeeb-i

**Comment by SimonPickup** [comment]
Please try to reproduce on the latest TestFlight beta (see #156).
