### ISSUE TITLE
Edit Folder: Ignore Patters are not shown

### ISSUE THREAD

**Issue by ivankovnatsky** [MobiusSync/MobiusSync#18]
details:

folder settings:
* in sharing i have "select all"
* file versioning to none
* other settings should be default

i'm using single folder with size around 16G.

phone: iPhone Xs
OS: 14.3

----

![Screenshot 2021-01-16 at 11 10 46](https://user-images.githubusercontent.com/75213/104808029-22a3f180-57ec-11eb-9e9b-2741f6878b78.png)

**Comment by sjpickup** [comment]
Hi there, thanks for raising this. I can definitely use this tab on my various devices. Does it "open" on any folders, or not at all? Has it never worked for you, or have you tried entering some ignore patterns and it's stopped displaying since? Have you changed other folder settings from defaults? Do you have many folders?

Can you please send screenshots of the other folder settings tabs, and which iPhone/iPad device and iOS version.

**Comment by ivankovnatsky** [comment]
> Does it "open" on any folders, or not at all?
i'm currently only using one folder across all of my devices. and it opens fine on any of my devices except phone.

> Has it never worked for you, or have you tried entering some ignore patterns and it's stopped displaying since?
i didn't play with it for too long, i just entered some ignore patterns on my pc, tried to view it on the phone, and the showed above behavior was reproduced.

> Have you changed other folder settings from defaults?
* in sharing i have "select all"
* file versioning to none
* other settings should be default

> Do you have many folders?
just one, size would be around 16G.

phone: iPhone Xs
OS: 14.3

**Comment by ivankovnatsky** [comment]
Thanks, not relevant anymore.
