### ISSUE TITLE
Support user-created folders under "On my iPhone"

### ISSUE THREAD

**Issue by jacrify** [MobiusSync/MobiusSync#197]
Folder is on root of iphone ("On my iphone"). Has simple name ("test"). 

Iphone xr ios 17.6.1. Latest version of app from store

**Comment by SimonPickup** [comment]
This error is for folders within iCloud Drive of a third-party file provider.

If still seeing this, can you please provide a screenshot from your Files app.

**Comment by datawench** [comment]
I can confirm exactly the same issue.

 I created a directory, “synctest”, On My iPad. It’s not on iCloud, it’s *actually* on my iPad, and nowhere else. In it is one simple text file. In Mobius, when I try to “pick external folder” and select that folder, I get the noted error.

I’m not sure what a screenshot would show, except to demonstrate that the directory is where I say it is.

I guess I should add that this the paid-for app.

iOS 17.6.1

möbius version:
v1.27.9-182-gc2bf95af1-i1.27.9, iOS (64-bit ARM)
"Gold Grasshopper"
Build 202407201420

**Comment by dominicwa** [comment]
Same here. Pro version. iPhone. Definitely local "On My iPhone" and not iCloud Drive. Can't create a folder anywhere except within the MobiusSync folder. Not in root, or in another app folder (Obsidian) or in a sub folder of either of those. Always get the "Unsupported folder" error.

(iOS18)

**Comment by jacrify** [comment]
![Screenshot of error](https://github.com/user-attachments/assets/033a41e1-dae4-4487-8d11-87a499b719a0)
![Screenshot inside mobius picking file](https://github.com/user-attachments/assets/bd5182c3-45d6-46d9-af49-de3e04c7a0dd)
![Screenshot from files](https://github.com/user-attachments/assets/d3fa8e10-0622-4104-b2e9-522d69f84d3d)

Screenshots attached. As I said in first post, folder is on root of my iphone. Still seeing it.

**Comment by SimonPickup** [comment]
OK, I have reproduced this.

1. Choosing a folder within the "Möbius Sync" folder **succeeds**
1.  Choosing another app's sandbox **succeeds**
1. Choosing a folder you've manually created **fails**

Out of interest, why do you want 3 over 1? Other than it makes your files more easily accessible in the Files app? (one less tap)?

**Comment by jacrify** [comment]
Top level folders don’t get “lost”.

**Comment by dominicwa** [comment]
> OK, I have reproduced this.
> 
> 1. Choosing a folder within the "Möbius Sync" folder **succeeds**
> 2. Choosing another app's sandbox **succeeds**
> 3. Choosing a folder you've manually created **fails**
> 
> Out of interest, why do you want 3 over 1? Other than it makes your files more easily accessible in the Files app? (one less tap)?

I didn't need 3 over 1. I needed 2 over 1... I was trying to sync an Obsidian vault. I _didn't_ succeed in that like you managed though.

However... I may have done something wonky (and this may help anyone stumbling here). During my testing I think I created my Obsidian folder on my iPhone manually (to then sync an existing vault on my Mac into). I did this because I had no existing vaults already on my phone (and so there was no Obsidian sandbox folder there already - the app seems to remove it altogether when there are no vaults). At one point I think actually managed to have two folders, both called Obsidian. One must have been my manually created folder and the other, the sandboxed app folder.

I haven't re-tested yet but I suspect that's why 2 → 1 didn't work for me.

To answer your question why options 3 or 2... and not just go for option 1... Obsidian (and many other iOS apps) will only scan their sandboxed folder to read in controlled / library data. Another example is VLC, which will only show files in the VLC sandbox file inside its library (even though it'll let you open/play/import files elsewhere on your phone). There's often subtle but impactful (to workflows) differences between files within the sandbox and outside them.

Why Apple had to go on this elaborate and awkward journey of trying to remove the concept of a filesystems to phone users is beyond me. Especially as these days they seem to be gradually unworking it and relayering in more advanced filesystem functionality again. (I mean, if apps can cross into other app sandboxes... why not just open the filesystem up rather than jumping all these frustrating hoops.)

Anyway... @SimonPickup, thanks heaps for your investigations. When I come back to this I'll check my above assumptions and give it another go 👍

**Comment by datawench** [comment]
All three options have uses, though I have to say 1 is what I use least.
The quickest example I can come up with for option 3 is syncing the local file used by beorg, which does seem to have a sandbox. But any collection of files that I want to work on across platforms would qualify. Chess databases also come to mind. The whole idea is to _not_ have to use any service like Dropbox, etc.

**Comment by SimonPickup** [comment]
This is now supported - creating a Syncthing Folder wihin "On my iPhone".

Now available in TestFight: https://github.com/MobiusSync/MobiusSync/discussions/194.
