### ISSUE TITLE
Incorporate Syncthing v1.18.4

### ISSUE THREAD

**Issue by hu3rror** [MobiusSync/MobiusSync#49]
Hi,

Is the work of development and maintenance still going on? 

I have noticed that the current version of Syncthing is version 1.13.1, which is much lower than the official version 1.18.

Thank you.

**Comment by ghost** [comment]
Given the total lack of responses to reported issues for several months now, I'm afraid we have to consider the project abandoned. How to go forward? I'm personally not using it or syncthing yet, due to a few showstopper issues (dot file handling, lack of support for extended attributes/tags), but would have liked to migrate from Resilio if they were resolved. So I'm personally not invested.

**Comment by SimonPickup** [comment]
We've got back to focussing on this and working on incorporating the untrusted encrypted devices. Will probably put this out to a TestFlight beta first.

**Comment by SimonPickup** [comment]
A beta version incorporating Syncthing 1.18.3 core is now in TestFlight. You can sign up to try it out here: https://github.com/MobiusSync/MobiusSync/discussions/56

**Comment by SimonPickup** [comment]
Beta in TestFlight now.
