### ISSUE TITLE
Improve background sync

### ISSUE THREAD

**Issue by sjpickup** [MobiusSync/MobiusSync#7]
Apple iOS restricts apps from running continuously in the background, so Möbius Sync can never truly run continuously (as a daemon) but apps can run for short times sporadically based on various conditions.

This Issue covers using the two background task modes available in iOS 13+ for requesting "quick syncs" and "power syncs".

Other issues will be created and linked here for different mechanisms to trigger background sync activity.

**Comment by rkjnsn** [comment]
I don't know if this is at all feasible given the various background limitations Apple has, but one though for the iOS to iOS case might be to use a push notification to attempt to wake the app on the other device. (This might need to be opt in, depending on the privacy implications of sending the push notification.)

**Comment by sjpickup** [comment]
**Quick syncs** which typically run for around 25s and **Power syncs** which typically run for 4m55s (but only when power is connected) is being added in **Möbius Sync v1.2**. iOS schedules these activities "intelligently" and the only direct configurability is the "minimum interval between syncs".

Möbius Sync supports configuring _minimum interval between syncs_ separately for **quick** and **power** syncs.

A local notification is also triggered to inform the user when these syncs are happening, and these can be enabled/disabled separately for **quick** and **power** syncs. The intention is to give visibility of the mechanisms used within iOS to schedule these so the user can take best advantage.

Apple documentation suggests that the background tasks are scheduled in anticipation of the user's (foreground) use of the app (as the core intention of this iOS feature is to pre-emptively load content ready for display the next time the app is opened).  This suggests that opening the app into the foreground more often will encourage more frequent task scheduling.

The app reports total durations of _Background sync since last opened_ and _Background sync in last 24h_. In testing, cumulative two hours of background sync has been seen per day.

Hopefully we can all learn how to best make use of this together.

**Comment by sjpickup** [comment]
Released in v1.2.

**Comment by cbeams** [comment]
I'm just installed Möbius Sync v1.12.1, gotten everything configured, but thus far have not seen any background syncs occur. I've configured the minimum quick sync interval to its lowest value (1m) and enabled rescans and left the phone alone for a few minutes, but when reopening and looking at the device info, it says `Background sync since last opened: 0` and `Background sync in last 24h: 0`. Perhaps the underlying iOS scheduler just doesn't run background syncs very eagerly? If this is normal behavior, it might be good to let folks know in the GUI, documentation, FAQ etc roughly how long one might need to wait to see a background sync actually occur.

**Comment by cbeams** [comment]
Update on the above: it's now been ~20 hours since installing and configuring Möbius Sync, and the UI still tells me that no background syncs have occurred. I'm running iOS 14.2 and I've double-checked that background sync is enabled for the app in iOS Settings. What could I be missing?

**Comment by cbeams** [comment]
A perhaps final update: I did finally start seeing syncs happen around an hour ago and 3 have now happened in total. So it seems that everything works as expected but that the first sync can take quite a while—even a full day—to occur.

So to reiterate my suggestion above, perhaps a more explicit warning about this is in order.

**Comment by sjpickup** [comment]
Thanks @cbeams, we've updated the FAQ on "Background sync".

I have also opened https://github.com/MobiusSync/MobiusSync/discussions/30 on the Discussions forum to allow people to share there experiences.

**Comment by cbeams** [comment]
Great to hear, thanks. Following up a bit further, I’ve come to believe that my delayed and infrequent sync experience is because I’m working on a years-old 1st-gen iPhone SE with very poor battery life. Perhaps iOS’s sync scheduling takes into account the current rate of battery consumption (always high in my case), and gets as conservative as possible. After ~2 days now, I’ve seen syncs occur as many as 8-10 times, mostly in the night when I’ve been plugged into power for hours. In any case, I predict that anyone working with a newer model phone and a fresh battery would have a shorter time to first sync and more frequent and regular syncs thereafter.
