### ISSUE TITLE
Error: Too many paths watched; scan optimisation for Receive Only folders

### ISSUE THREAD

**Issue by 497e0bdf29873** [MobiusSync/MobiusSync#73]
I use my iPhone as a fancy wireless USB stick, storing several Mercurial repositories of private projects (numerical codes and LaTeX source of past scientific papers etc.) there using MoebiusSync. (Thanks for fixing the issue with dot-files, so I could make the switch from ResilioSync!) The respective folder has 90997 files, and gives me the error:
```
error while traversing /private/var/mobile/Containers/Data/Application/…/Documents/repos/…: too many paths watched fd=4001
```

Now, I can of course disable watching, and I really don't know if this has any real difference on iOS—does MoebiusSync get notifications while it's in the background?

In any case, with watching disabled (and I cannot test with watching enabled, as I get the error above), the scanning of the folder takes a minute, which is an issue for background synchronisation and makes manual synchronisation also slow. With a folder that's actually used and modified on the iPhone, there's probably no way around this. _However_, the repository folder is `Receive Only`; it's not meant to be modified on the iPhone, so perhaps there is a way to do away with the scan?

I am aware that this request may be more relevant for the SyncThing core.

**Comment by SimonPickup** [comment]
Nice to hear about your use-case, thanks.

File watching is basically useless in MöbiusSync since sync runs cannot be triggered from this anyway unless the app is running in the foreground. Hence we turned off file watching by default in #1.

I'm not sure how the scan works for `Receive Only` folders, but yes, surely it's more of a SyncThing core issue than anything specific to iOS.

Closing.
